-- illustration-descriptions.csv(評価者作成スプレッドシートの詳細説明列)より、
-- display_order基準でillustrations.descriptionを一括投入する。

update illustrations set description = 'おやつ　食器の使用　外食　飲み物　はし・フォーク・スプーン・ナイフの使用　コップの使用' where display_order = 1;
update illustrations set description = '整髪　鼻のケア　手洗い　歯磨き　洗顔' where display_order = 2;
update illustrations set description = '更衣(上半身)　更衣(下半身)　ジッパーをとめる　靴下　靴を結ぶ　メガネやコンタクトの着脱' where display_order = 3;
update illustrations set description = '自分の体を洗う　風呂/シャワー　清拭　体を清潔に保つ' where display_order = 4;
update illustrations set description = '排尿管理　排便管理　トイレ動作　おしっこをする前に知らせる　(自分で)パンツを脱いでおしっこをする' where display_order = 5;
update illustrations set description = '滑りやすい道を歩く　道や程を歩く　歩行/車椅子/はいはい' where display_order = 6;
update illustrations set description = '階段昇降　エレベーター　エスカレーター' where display_order = 7;
update illustrations set description = '買い物に行く　買い物をするための計算・支払い' where display_order = 8;
update illustrations set description = '体作り運動　医療サービスを受ける　生活習慣の形成　十分な睡眠　栄養バランスのよい食事　薬を飲む' where display_order = 9;
update illustrations set description = '小遣いの管理　金銭の(適切な)使用　銀行やATMの使用' where display_order = 10;
update illustrations set description = '放課後の過ごし方　スケジュール・日課の管理、好きなことをする時間を持つ、放課後の過ごし方' where display_order = 11;
update illustrations set description = '机をきれいに保つ　自分の部屋　ベッドルーム　掃除機の使用' where display_order = 12;
update illustrations set description = '洗濯物　衣類　ご飯の準備・片付け　ゴミ出し　おつかい' where display_order = 13;
update illustrations set description = '食事を作る' where display_order = 14;
update illustrations set description = 'ストレス/心理的欲求への対処　落ち着くために性的活動を行う　落ち着く　眠る' where display_order = 15;
update illustrations set description = 'バス　電車　船　飛行機　タクシー' where display_order = 16;
update illustrations set description = '免許の取得' where display_order = 17;
update illustrations set description = '友達と遊ぶ　友達の家に遊びに行く　友達の家に泊まる　挨拶をする' where display_order = 18;
update illustrations set description = '先生に質問する　援助を求める' where display_order = 19;
update illustrations set description = '家族と遊ぶ　家族関係　兄弟関係　親戚関係　家族と団欒の時間を持つ' where display_order = 20;
update illustrations set description = '適切な態度で接する' where display_order = 21;
update illustrations set description = '思春期の不安・悩みとその解決　男女相互の理解　適切な態度で接する　適切な距離を保って接する' where display_order = 22;
update illustrations set description = '近所づきあい　身近な人との関係　よく知らない人との関係' where display_order = 23;
update illustrations set description = '適切な態度で接する　挨拶をする' where display_order = 24;
update illustrations set description = '電話でのやりとり、携帯電話の使用' where display_order = 25;
update illustrations set description = '手紙・メールでのやりとり　連絡帳' where display_order = 26;
update illustrations set description = '国語　数学　英語　理科　　社会　文字や数字の使用' where display_order = 27;
update illustrations set description = '絵画　描画　工芸　鑑賞　合唱' where display_order = 28;
update illustrations set description = '体操・基礎体力を養う運動　走る　ジャンプする　水泳　器械体操' where display_order = 29;
update illustrations set description = '携帯電話・パソコン・インターネットの使用' where display_order = 30;
update illustrations set description = '宿題をする　宿題を見てもらう' where display_order = 31;
update illustrations set description = '課題を終える　ノートをとる　挙手・発言' where display_order = 32;
update illustrations set description = '学校の準備　教材の準備　ロッカー・机の整理' where display_order = 33;
update illustrations set description = '安全な登下校ができる' where display_order = 34;
update illustrations set description = '配膳　後片付け　食べ終える' where display_order = 35;
update illustrations set description = '学校の部活動　地域のクラブ　サークル活動' where display_order = 36;
update illustrations set description = '机を運ぶ　黒板を消す　ほうきなどの使用' where display_order = 37;
update illustrations set description = '教室で過ごす　校庭で過ごす' where display_order = 38;
update illustrations set description = '学校/クラスの中での役割　当番として決められた活動　保健委員会・飼育係・給食当番など' where display_order = 39;
update illustrations set description = '遠足・集団宿泊行事　勤労生産・集団宿泊的行事' where display_order = 40;
update illustrations set description = '儀式的な行事' where display_order = 41;
update illustrations set description = '文化的行事' where display_order = 42;
update illustrations set description = '健康・安全・体育的な行事' where display_order = 43;
update illustrations set description = '進路情報の取得　進路の選択・決定　職業訓練　将来設計　学ぶこと・働くことの意義の理解' where display_order = 44;
update illustrations set description = '塾　通信教育　就学前教育' where display_order = 45;
update illustrations set description = '漢字検定　英語検定　PC検定　簿記　自動車免許' where display_order = 46;
update illustrations set description = '無報酬の仕事' where display_order = 47;
update illustrations set description = '報酬を伴う仕事' where display_order = 48;
update illustrations set description = '読書　漫画　絵本　読み聞かせ' where display_order = 49;
update illustrations set description = '歌う　楽器　音楽の勉強　音遊び　リズム遊び' where display_order = 50;
update illustrations set description = 'ミニカー　プラモデル　人形遊び　パズル　積み木　ブロック　ままごと' where display_order = 51;
update illustrations set description = '遊具で遊ぶ　縄跳び　鬼ごっこ　缶けり　公園で遊ぶ' where display_order = 52;
update illustrations set description = '創作する　絵を描く　塗り絵　物語をつくる' where display_order = 53;
update illustrations set description = 'テレビ/DVDを観る、音楽を聴く、機器の操作、携帯音楽プレーヤーの使用' where display_order = 54;
update illustrations set description = 'TVゲーム　携帯ゲーム　カードゲーム　ボードゲーム' where display_order = 55;
update illustrations set description = 'サッカー　野球　バレーボール　バスケットボール　ドッチボール　テニス　卓球　ボール遊び' where display_order = 56;
update illustrations set description = 'バレエ　リトミック　　ダンス' where display_order = 57;
update illustrations set description = '格闘技　剣道　柔道　空手' where display_order = 58;
update illustrations set description = 'かけっこ、50m走、マラソン、屋内、屋外' where display_order = 59;
update illustrations set description = '海　プール　水遊び　スイミング' where display_order = 60;
update illustrations set description = '自電車　スケートボード　ローラーブレード' where display_order = 61;
update illustrations set description = '夏祭り　町内会　花火大会　子ども会' where display_order = 62;
update illustrations set description = '旅行　観光' where display_order = 63;
update illustrations set description = 'ピクニック　ハイキング　ウォータースポーツ　ウインタースポーツ　釣り　海水浴　BBQ' where display_order = 64;
update illustrations set description = '園芸　ペットの世話　乗馬' where display_order = 65;
update illustrations set description = '遊園地　水族館　動物園' where display_order = 66;
update illustrations set description = '外食，一緒に買い物　エレベーターの利用　百貨店　ショッピングセンター' where display_order = 67;
update illustrations set description = 'ライブ　コンサート　映画' where display_order = 68;
